export const PREFERENCES_NAME = 'MseaPreferences';
export const MESSAGE_DURATION = 3000;

export class UserInfoKey {
    static readonly AUTH = "authKey";
    static readonly SALT = "saltKey";
    static readonly FORMHASH = "formhashKey";
    static readonly UID = "uidKey";
    static readonly NAME = "nameKey";
    static readonly LEVEL = "levelKey";
    static readonly AVATAR = "avatarKey";
    static readonly FRIEND = "friendKey";
    static readonly REPLY = "replyKey";
    static readonly TOPIC = "topicKey";
    static readonly INTEGRAL = "integralKey";
    static readonly BITS = "bitsKey";
    static readonly VIOLATION = "violationKey";
}